name: mtl-gnn-dta
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # Python
  - python=3.10
  
  # Core Deep Learning
  - pytorch=2.0.1
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - cudatoolkit=11.8
  
  # PyTorch Geometric and dependencies
  - pyg=2.3.1
  - pytorch-scatter
  - pytorch-sparse
  - pytorch-cluster
  - pytorch-spline-conv
  
  # Scientific Computing
  - numpy=1.24.3
  - scipy=1.10.1
  - pandas=2.0.3
  - scikit-learn=1.3.0
  
  # Molecular Processing
  - rdkit=2023.03.3
  - biopython=1.81
  - openmm=8.0.0
  - pdbfixer=1.9
  
  # Visualization
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - plotly=5.15.0
  
  # Development Tools
  - jupyter=1.0.0
  - ipykernel=6.25.0
  - jupyterlab=4.0.5
  - ipywidgets=8.1.0
  
  # Data Processing
  - h5py=3.9.0
  - pyarrow=12.0.1
  - fastparquet=2023.7.0
  
  # Utilities
  - tqdm=4.66.1
  - pyyaml=6.0.1
  - click=8.1.6
  - rich=13.5.2
  - python-dotenv=1.0.0
  
  # Testing and Code Quality
  - pytest=7.4.0
  - pytest-cov=4.1.0
  - black=23.7.0
  - flake8=6.1.0
  - mypy=1.5.1
  
  # Additional conda packages
  - pip
  - setuptools
  - wheel
  
  # Pip dependencies (packages not available in conda)
  - pip:
    # Protein Language Models
    - fair-esm==2.0.0
    - transformers==4.31.0
    
    # DGL for additional graph operations
    - dgl==1.1.2
    - dgllife==0.3.2
    
    # ML Experiment Tracking
    - wandb==0.15.8
    - tensorboard==2.14.0
    - optuna==3.3.0
    
    # Additional utilities
    - einops==0.6.1
    - omegaconf==2.3.0
    
    # Documentation
    - sphinx==7.1.2
    - sphinx-rtd-theme==1.3.0
    - sphinxcontrib-napoleon==0.7